### ISSUE TITLE
The library does not support device name with more than 30 characters

### ISSUE THREAD

**Issue by ntth4** [ynezz/librs232#15]
The support for serial device file name longer than 30 characters is needed for Linux, where a USB-to-serial device may have a very long name.  The actual device name for USB-to-serial device, not the symlink, is used to achieve consistent name after the USB device is unplugged/plugged.  An example device name on Ubuntu: /dev/serial/by-id/usb_to_serial_ftdi_FTDIXYZ_port0_0.

**Comment by ynezz** [comment]
This project is not maintained anymore and marked as archived. I've lost interest in closed source operating systems like Windows, so I simply don't want to spend my time on anything related to the Windows ecosystem.

Anyway @srdgame has [forked this project](https://github.com/srdgame/librs232) and it seems to be alive and in a good shape so feel free to look at it as a viable alternative.
