### ISSUE TITLE
rs232_end

### ISSUE THREAD

**Issue by www220** [ynezz/librs232#16]
没有任何地方调用rs232_end，导致内存泄露

**Comment by ynezz** [comment]
This project is not maintained anymore and marked as archived. I've lost interest in closed source operating systems like Windows, so I simply don't want to spend my time on anything related to the Windows ecosystem.

Anyway @srdgame has [forked this project](https://github.com/srdgame/librs232) and it seems to be alive and in a good shape so feel free to look at it as a viable alternative.
