### ISSUE TITLE
fails to install from luarocks

### ISSUE THREAD

**Issue by comotion** [ynezz/librs232#21]
sudo luarocks-5.1 install luars232
Installing https://rocks.moonscript.org/luars232-1.0.3-1.src.rock...
Using https://rocks.moonscript.org/luars232-1.0.3-1.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/rs232.c -o src/rs232.o -DLUAROCKS_HACK -std=gnu99 -Iinclude
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/rs232_posix.c -o src/rs232_posix.o -DLUAROCKS_HACK -std=gnu99 -Iinclude
gcc -O2 -fPIC -I/usr/include/lua5.1 -c bindings/lua/luars232.c -o bindings/lua/luars232.o -DLUAROCKS_HACK -std=gnu99 -Iinclude
gcc -shared -o luars232.so -L/usr/lib src/rs232.o src/rs232_posix.o bindings/lua/luars232.o

Error: Directory 'invalid' not found

**Comment by ynezz** [comment]
Hi,

sorry, but I'm not author of that rock file and I don't use those packages personally, so I can't help you with that error. Please try to report it in appropriate place instead, thanks.

**Comment by comotion** [comment]
I understand that you do not use the rock module system. I feel that a working rock would increase adoption of this code and hope that you consider including one once there is a working rockspec available.

**Comment by ynezz** [comment]
I didn't published the source code to increase it's adoption, I've just thought, that it might be useful. Sorry, but I simply don't have time to support every possible configuration, package manager or build system. 

This issue is simply problem with the rockspec, try to delete following lines:

   copy_directories = {
      "invalid"
   },

**Comment by comotion** [comment]
This library is useful and this is why I care about the rockspec - it makes it possible for me to ship code that depends on the lib. The rockspec fellas have fixed the rockspec now :+1
