### ISSUE TITLE
documentation for lua_port_strerror is incorrect

### ISSUE THREAD

**Issue by Siapran** [ynezz/librs232#23]
[bindings/lua/luars232.c#L322](https://github.com/ynezz/librs232/blob/master/bindings/lua/luars232.c#L322)

```
/*
 * print(port:error_tostring(error))
 */
```

should be:

```
/*
 * print(rs232.error_tostring(error))
 */
```

**Comment by ynezz** [comment]
This project is not maintained anymore and marked as archived. I've lost interest in closed source operating systems like Windows, so I simply don't want to spend my time on anything related to the Windows ecosystem.

Anyway @srdgame has [forked this project](https://github.com/srdgame/librs232) and it seems to be alive and in a good shape so feel free to look at it as a viable alternative.
