### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by itubal** [ynezz/librs232#25]
[josema@marengo librs232]$ ./autogen.sh
running: autoreconf --force --install --symlink --verbose
./autogen.sh: línea 6: autoreconf: no se encontró la orden
error: while running 'autoreconf --force --install --symlink --verbose'
[josema@marengo librs232]$ 

"no se encontró la orden" means "command not found" or similar

**Comment by itubal** [comment]
I'd installed it from luarocks.
Now i get an error.
Linux Fedora 25
the example program:
local rs232 = require "rs232"

local p, e = rs232.port('ttyS0',{
  baud         = '57600';
  data_bits    = '_8';
  parity       = 'NONE';
  stop_bits    = '_1';
  flow_control = 'OFF';
  rts          = 'ON'
})
num,err = p:open()
print (num)
print (err)

The result:
nil
[RS232][OPEN] open error (2)

**Comment by ynezz** [comment]
You're using probably example from different project, which is not compatible with my library. Try to look at the [example](https://github.com/ynezz/librs232/blob/master/doc/example.lua) for this project.

```lua
e, p = rs232.open('/dev/ttyS0')
p:set_baud_rate(rs232.RS232_BAUD_57600)
```
