### ISSUE TITLE
Does rs232_end() wait for transfers to complete?

### ISSUE THREAD

**Issue by afalkenhahn** [ynezz/librs232#27]
I'm seeing an issue with `rs232_test.c`. Looks like `rs232_end()` doesn't wait for the transfer to complete before shutting down which can lead to some misbehaviour. See here for a discussion:
https://stackoverflow.com/questions/53804659/serial-port-receives-two-more-bytes-than-sent

**Comment by ynezz** [comment]
This project is not maintained anymore and marked as archived. I've lost interest in closed source operating systems like Windows, so I simply don't want to spend my time on anything related to the Windows ecosystem.

Anyway @srdgame has [forked this project](https://github.com/srdgame/librs232) and it seems to be alive and in a good shape so feel free to look at it as a viable alternative.
